name: llm_voice_assistant
channels:
  - defaults
dependencies:
  - pip
  - python==3.9.18
  - typer
  - pyaudio
  - openai
  - python-dotenv
  - pip:
      - cffi==1.16.0
      - charset-normalizer==3.3.2
      - coloredlogs==15.0.1
      - flatbuffers==24.3.7
      - humanfriendly==10.0
      - idna==3.6
      - joblib==1.3.2
      - mpmath==1.3.0
      - onnxruntime==1.17.1
      - openwakeword==0.6.0
      - packaging==24.0
      - piper-phonemize==1.1.0
      - piper-tts==1.2.0
      - protobuf==5.26.0
      - pycparser==2.21
      - requests==2.31.0
      - scikit-learn==1.4.1.post1
      - scipy==1.12.0
      - srt==3.5.3
      - sympy==1.12
      - tflite-runtime==2.14.0
      - threadpoolctl==3.3.0
      - tqdm==4.66.2
      - urllib3==2.2.1
      - vosk==0.3.45
      - websockets==12.0
