name: llm_voice_assistant
channels:
  - defaults
dependencies:
  - python==3.9.18
  - pyaudio
  - typer
  - numpy
  - openai
  - python-dotenv
  - pip:
      - cffi==1.16.0
      - charset-normalizer==3.3.2
      - coloredlogs==15.0.1
      - filelock==3.13.3
      - flatbuffers==24.3.7
      - fsspec==2024.3.1
      - huggingface-hub==0.22.2
      - humanfriendly==10.0
      - idna==3.6
      - jinja2==3.1.2
      - joblib==1.3.2
      - llvmlite==0.42.0
      - markupsafe==2.1.3
      - more-itertools==10.2.0
      - mpmath==1.3.0
      - networkx==3.2.1
      - numba==0.59.1
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.19.3
      - nvidia-nvjitlink-cu12==12.4.127
      - nvidia-nvtx-cu12==12.1.105
      - onnxruntime==1.17.1
      - openai-whisper==20231117
      - openwakeword==0.6.0
      - packaging==24.0
      - pillow==10.2.0
      - piper-phonemize==1.1.0
      - piper-tts==1.2.0
      - protobuf==5.26.0
      - pycparser==2.21
      - pyyaml==6.0.1
      - regex==2023.12.25
      - requests==2.31.0
      - safetensors==0.4.2
      - scikit-learn==1.4.1.post1
      - scipy==1.12.0
      - srt==3.5.3
      - stt==1.4.0
      - sympy==1.12
      - tflite-runtime==2.14.0
      - threadpoolctl==3.3.0
      - tiktoken==0.6.0
      - tokenizers==0.15.2
      - torch==2.2.2
      - tqdm==4.66.2
      - triton==2.2.0
      - urllib3==2.2.1
      - vosk==0.3.45
      - websockets==12.0
