name: llm_voice_assistant
channels:
  - defaults
dependencies:
  - pip
  - python==3.9.18
  - typer
  - pyaudio
  - pip:
      - certifi==2024.2.2
      - charset-normalizer==3.3.2
      - coloredlogs==15.0.1
      - flatbuffers==24.3.7
      - humanfriendly==10.0
      - idna==3.6
      - joblib==1.3.2
      - mpmath==1.3.0
      - numpy==1.26.4
      - onnxruntime==1.17.1
      - openwakeword==0.6.0
      - packaging==24.0
      - protobuf==5.26.0
      - requests==2.31.0
      - scikit-learn==1.4.1.post1
      - scipy==1.12.0
      - sympy==1.12
      - tflite-runtime==2.14.0
      - threadpoolctl==3.3.0
      - tqdm==4.66.2
      - urllib3==2.2.1
